name: Model Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ./data
        key: ${{ runner.os }}-pip-data-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-data-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up environment
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
        echo "TORCH_NUM_THREADS=4" >> $GITHUB_ENV
        
    - name: Run tests
      run: |
        pytest tests/

    - name: Check model parameters and accuracy
      run: |
        # Print Python and PyTorch versions for debugging
        python -c "import sys; print(f'Python version: {sys.version}')"
        python -c "import torch; print(f'PyTorch version: {torch.__version__}')"
        python -c "import torch; print(f'CUDA available: {torch.cuda.is_available()}')"
        
        # Run the model check with detailed logging
        python check_model.py